### ISSUE TITLE
1.16 Support

### ISSUE THREAD

**Issue by sid-engel** [ZeppelinForDays/ReportPlus#12]
Hello there, could we get an update for 1.16 support? Thanks!

```
04.07 12:30:02 [Server] INFO [ReportPlus] Enabling ReportPlus v1.3.2
04.07 12:30:02 [Server] ERROR Error occurred while enabling ReportPlus v1.3.2 (Is it up to date?)
04.07 12:30:02 [Server] INFO java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.SKULL_ITEM
04.07 12:30:02 [Server] INFO at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_252]
04.07 12:30:02 [Server] INFO at org.bukkit.Material.valueOf(Material.java:88) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at net.zeppelin.reportplus.inventories.MainInventory.loadContents(MainInventory.java:38) ~[?:?]
04.07 12:30:02 [Server] INFO at net.zeppelin.reportplus.utils.InventoryHandler.loadInventories(InventoryHandler.java:54) ~[?:?]
04.07 12:30:02 [Server] INFO at net.zeppelin.reportplus.main.ReportPlusPlugin.onEnable(ReportPlusPlugin.java:69) ~[?:?]
04.07 12:30:02 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
04.07 12:30:02 [Server] INFO [ReportPlus] Disabling ReportPlus v1.3.2
04.07 12:30:02 [Server] ERROR Error occurred while disabling ReportPlus v1.3.2 (Is it up to date?)
04.07 12:30:02 [Server] INFO java.lang.NullPointerException: null
04.07 12:30:02 [Server] INFO at net.zeppelin.reportplus.main.ReportPlusPlugin.saveReportsToConfig(ReportPlusPlugin.java:177) ~[?:?]
04.07 12:30:02 [Server] INFO at net.zeppelin.reportplus.main.ReportPlusPlugin.onDisable(ReportPlusPlugin.java:96) ~[?:?]
04.07 12:30:02 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:02 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-46]
04.07 12:30:03 [Multicraft] Skipped 15 lines due to rate limit (30/s)
```

**Comment by ZeppelinForDays** [comment]
I’ll work on it as soon as I get some time.

**Comment by ZeppelinForDays** [comment]
Fixed.
